version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - php
      - backend1
    networks:
      - app-network

  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./php:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=256M
    networks:
      - app-network

  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: rootoor
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend1:
    build:
      context: ./backend1
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=user
      - DB_PASS=userpassword
      - DB_NAME=app_db
    depends_on:
      - mariadb
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
